In [14]:
import pandas as pd, numpy as np
from numpy import log
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.tools.eval_measures import rmse
np.random.seed(5647)

df = pd.read_csv("/Users/pranjal/Desktop/Quantitative-Macroeconomics/Examples/annual-us.csv")
df = df[18+34:-2]
df

,DATE,GDPC1,AWHI,RKNANPUSA666NRUG,PCECCA,GPDIC1
52,1981-01-01,6935.1532500000000000,71.4333333333333333,29770398.0,4310.034,940.0510000000000000
53,1982-01-01,6810.1200000000000000,68.8250000000000000,30400942.0,4373.125,821.9737500000000000
54,1983-01-01,7122.2905000000000000,69.8250000000000000,31125584.0,4620.691,898.6887500000000000
55,1984-01-01,7637.7040000000000000,74.0333333333333333,32101154.0,4863.775,1143.9515000000000000
56,1985-01-01,7956.1695000000000000,76.0083333333333333,33160380.0,5115.597,1143.2232500000000000
57,1986-01-01,8231.6635000000000000,77.2333333333333333,34217176.0,5326.775,1145.0302500000000000
58,1987-01-01,8516.4182500000000000,79.5583333333333333,35245908.0,5507.629,1177.5695000000000000
59,1988-01-01,8872.1542500000000000,81.8833333333333333,36263700.0,5737.676,1206.6217500000000000
60,1989-01-01,9197.9975000000000000,83.8416666666666667,37283484.0,5904.965,1255.4312500000000000
61,1990-01-01,9371.4680000000000000,84.2250000000000000,38223836.0,6023.895,1223.0352500000000000
62,1991-01-01,9361.3220000000000000,82.4416666666666667,38987084.0,6034.769,1142.1105000000000000
63,1992-01-01,9691.0687500000000000,83.0166666666666667,39793464.0,6256.853,1225.3305000000000000
64,1993-01-01,9957.7462500000000000,85.4333333333333333,40663208.0,6474.82,1323.3020000000000000
65,1994-01-01,10358.9232500000000000,89.0083333333333333,41620812.0,6725.674,1479.8115000000000000
66,1995-01-01,10636.9787500000000000,91.4083333333333333,42632688.0,6924.116,1527.2895000000000000
67,1996-01-01,11038.2660000000000000,93.6000000000000000,43758388.0,7164.377,1660.7992500000000000
68,1997-01-01,11529.1570000000000000,96.9250000000000000,44977188.0,7434.153,1850.2095000000000000
69,1998-01-01,12045.8240000000000000,99.3250000000000000,46345160.0,7828.985,2026.3020000000000000
70,1999-01-01,12623.361000000000,101.5000000000000000,47827892.0,8250.271,2198.7070000000000000
71,2000-01-01,13138.035250000000,103.4500000000000000,49368260.0,8665.826,2346.7312500000000000
72,2001-01-01,13263.417000000000,102.0333333333333333,50734816.0,8880.425,2214.6262500000000000
73,2002-01-01,13488.357000000000,99.9916666666666667,51925832.0,9106.249,2195.4850000000000000
74,2003-01-01,13865.519250000000,98.6666666666666667,53184000.0,9394.39,2290.3707500000000000
75,2004-01-01,14399.696000000000,100.2666666666666667,54572836.0,9748.558,2502.5520000000000000
76,2005-01-01,14901.269000000000,102.8166666666666667,56084488.0,10093.793,2670.5650000000000000
77,2006-01-01,15315.943250000000,105.7333333333333333,57575292.0,10386.247,2752.4130000000000000
78,2007-01-01,15623.871500000000,107.3000000000000000,58915288.0,10638.728,2684.1375000000000000
79,2008-01-01,15642.962000000000,106.0500000000000000,59981812.0,10654.688,2462.9115000000000000
80,2009-01-01,15236.262250000000,98.8833333333333333,60510768.0,10515.592,1941.9702500000000000
81,2010-01-01,15648.991000000000,98.9500000000000000,61054676.0,10716.008,2216.4777500000000000
82,2011-01-01,15891.534000000000,101.4083333333333333,61672648.0,10898.345,2362.1282500000000000
83,2012-01-01,16253.970000000000,104.1250000000000000,62435632.0,11047.363,2621.7540000000000000
84,2013-01-01,16553.347500000000,106.1000000000000000,63232928.0,11211.711,2801.4732500000000000
85,2014-01-01,16932.051750000000,108.4916666666666667,64124212.0,11515.312,2959.1985000000000000
86,2015-01-01,17390.295250000000,110.9250000000000000,65057816.0,11892.947,3121.7557500000000000
87,2016-01-01,17680.273750000000,112.5833333333333333,65974060.0,12187.676,3089.9140000000000000
88,2017-01-01,18079.084000000000,114.7250000000000000,66942704.0,12483.677,3212.4750000000000000
89,2018-01-01,18606.786500000000,117.1166666666666667,68007352.0,12845.029,3394.8452500000000000
90,2019-01-01,19032.671500000000,118.2333333333333333,69059064.0,13126.286,3510.6215000000000000
91,2020-01-01,18384.687250000000,110.7416666666666667,.,12629.897,3316.2230000000000000

In [ ]:

df['AWHI']=df['AWHI'].astype(float)
df['GDPC1']=df['GDPC1'].astype(float)
df["AWHI"] = log(df["AWHI"]);
df["GDPC1"] = log(df["GDPC1"]);
df["Z"] = df["GDPC1"] - (2/3)*df["AWHI"]; # TFP Calculation
df["Z(t-1)"] = df["Z"].shift(1)
df["T"] = range(1,df.shape[0]+1,1)
df = df.iloc[16:]

In [12]:
df[1:20]

,DATE,GDPC1,AWHI,RKNANPUSA666NRUG,PCECCA,GPDIC1,Z,Z(t-1),T
69,1998-01-01,9.396473,4.598397,46345160.0,7828.985,2026.3020000000000000,6.330875,6.303343,18
70,1999-01-01,9.443304,4.620059,47827892.0,8250.271,2198.7070000000000000,6.363265,6.330875,19
71,2000-01-01,9.483267,4.639088,49368260.0,8665.826,2346.7312500000000000,6.390541,6.363265,20
72,2001-01-01,9.492765,4.625300,50734816.0,8880.425,2214.6262500000000000,6.409232,6.390541,21
73,2002-01-01,9.509582,4.605087,51925832.0,9106.249,2195.4850000000000000,6.439524,6.409232,22
74,2003-01-01,9.537160,4.591747,53184000.0,9394.39,2290.3707500000000000,6.475996,6.439524,23
75,2004-01-01,9.574962,4.607833,54572836.0,9748.558,2502.5520000000000000,6.503074,6.475996,24
76,2005-01-01,9.609202,4.632947,56084488.0,10093.793,2670.5650000000000000,6.520570,6.503074,25
77,2006-01-01,9.636650,4.660920,57575292.0,10386.247,2752.4130000000000000,6.529369,6.520570,26
78,2007-01-01,9.656555,4.675629,58915288.0,10638.728,2684.1375000000000000,6.539469,6.529369,27
79,2008-01-01,9.657776,4.663911,59981812.0,10654.688,2462.9115000000000000,6.548503,6.539469,28
80,2009-01-01,9.631434,4.593941,60510768.0,10515.592,1941.9702500000000000,6.568806,6.548503,29
81,2010-01-01,9.658162,4.594615,61054676.0,10716.008,2216.4777500000000000,6.595085,6.568806,30
82,2011-01-01,9.673542,4.619155,61672648.0,10898.345,2362.1282500000000000,6.594105,6.595085,31
83,2012-01-01,9.696092,4.645592,62435632.0,11047.363,2621.7540000000000000,6.599031,6.594105,32
84,2013-01-01,9.714344,4.664382,63232928.0,11211.711,2801.4732500000000000,6.604756,6.599031,33
85,2014-01-01,9.736964,4.686673,64124212.0,11515.312,2959.1985000000000000,6.612515,6.604756,34
86,2015-01-01,9.763668,4.708854,65057816.0,11892.947,3121.7557500000000000,6.624431,6.612515,35
87,2016-01-01,9.780205,4.723694,65974060.0,12187.676,3089.9140000000000000,6.631076,6.624431,36